### ISSUE TITLE
Paginação e deleção

### ISSUE THREAD

**Issue by acenelio** [leandroaugustolelis/client#1]
Olá Leandro. Seu projeto está quase lá. Por favor corrija os dois itens a seguir e reenvie a tarefa lá na nossa plataforma:

1) Favor incluir a paginação no endpoint que recupera os clientes.

2) Favor retirar o corpo da requisição de deleção lá no seu ClientResource.

Não deixe de testar todas requisições conforme nós mostramos lá no documento do enunciado do trabalho, ok? Abraços e continuo à disposição.

**Comment by leandroaugustolelis** [comment]
Obrigado pelo feedback Nelio, já enviei o fix.
